global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['192.168.100.10:9100']  # VM IP

  - job_name: 'flask_app'
    static_configs:
      - targets: ['192.168.100.10:5000']  # Flask app with prometheus exporter



