pipeline {
  agent any
  stages {
    stage('Clone') {
      steps {
        git 'https://github.com//TechieVinita/devops-internship-project.git'
      }
    }
    stage('Setup') {
      steps {
        sh '''
        python3 -m venv venv
        source venv/bin/activate
        pip install -r flask_app/requirements.txt
        '''
      }
    }
    stage('Restart App') {
      steps {
        sh 'sudo systemctl restart flask_app'
      }
    }
    stage('Test') {
      steps {
        sh 'curl http://localhost:5000/'
      }
    }
  }
}
